### PR TITLE
Update UMD wrapper.

### PR DESCRIPTION
**Pull request by percyhanna**
Fixes an issue where React might not be loaded properly when using the NodeJS implementation of the UMD wrapper.

### CODE REVIEW

**Comment by percyhanna** [comment]
@BlueVajra could you try this modification locally and see if it addresses your problems?

**Comment by BlueVajra** [comment]
@percyhanna will check it out today, will let you know what I find. Thanks for looking into it!

**Comment by BlueVajra** [comment]
:+1: @percyhanna that fix works perfectly.. thanks again... I am loving the rquery syntax btw.

**Comment by percyhanna** [comment]
Thanks for the bug report and feedback. rquery has proved very useful for some great unit and integration tests with React.

**Comment by percyhanna** [comment]
Released as v2.0.1.

**Pull request merged**
